### ISSUE TITLE
[WPF] Resizing problem

### ISSUE THREAD

**Issue by stefmancio** [wieslawsoltes/Core2D#100]
Hi,
In the WPF project, when i try to resize the page... if i set size values bigger than around 1300, the page doesn't resize as  as indicated by the entered values,

![image](https://user-images.githubusercontent.com/54392464/79721439-9e672100-82e2-11ea-85e8-ab7662a01361.png)

There is a way to encrease the max a bit? like 3000 ?
It would be perfect...
Thank you for your attention...

**Comment by wieslawsoltes** [comment]
It's a bug.

WPF version is no longer developed.

If you can please use Avalonia version from master branch.

**Comment by wieslawsoltes** [comment]
@stefmancio This is issue not with Core2D but with WPF clipping the drawing area. This is probably fixable but it's a lot of work to implement the controls.
![WPF-Resizing-Issue](https://user-images.githubusercontent.com/2297442/79738625-4558b680-82fd-11ea-80c4-b58415c8ff28.png)

**Comment by wieslawsoltes** [comment]
The source of this issue is in how WPF handles layout for ZoomBorder control responsible for pan and zoom functionality.

So to fix this we need to fix ZoomBorder.

https://github.com/wieslawsoltes/PanAndZoom/blob/ba4a963e99880ddb2ceadf1b9c76569ab7ebb863/src/Wpf.Controls.PanAndZoom/ZoomBorder.cs#L18

Otherwise you can replace ZoomBorder with ScrollViewer but you will lose pan and zoom functionality, also you need to implement proper input handling.

**Comment by stefmancio** [comment]
> @stefmancio This is issue not with Core2D but with WPF clipping the drawing area. This is probably fixable but it's a lot of work to implement the controls.
> ![WPF-Resizing-Issue](https://user-images.githubusercontent.com/2297442/79738625-4558b680-82fd-11ea-80c4-b58415c8ff28.png)

@stefmancio This is issue not with Core2D but with WPF clipping the drawing area. This is probably fixable but it's a lot of work to implement the controls.
![WPF-Resizing-Issue](https://user-images.githubusercontent.com/2297442/79738625-4558b680-82fd-11ea-80c4-b58415c8ff28.png)

_Originally posted by @wieslawsoltes in https://github.com/wieslawsoltes/Core2D/issues/100#issuecomment-616438774_

I though was this the issue.. I just tried to ask, hoping fo different answer :)
I will take a look at ZoomBorder  'cause i need pan and zoom and i have to stay wpf due to the directive they gave me, thank you  very much!

**Comment by wieslawsoltes** [comment]
> I though was this the issue.. I just tried to ask, hoping fo different answer :)
> I will take a look at ZoomBorder 'cause i need pan and zoom and i have to stay wpf due to the directive they gave me, thank you very much!

As I was investigating the pan and zoom issue I have remembered that this was an issue long time ago. Good luck finding solution. 

I think to fix pan and zoom one has to take different approach. I have nice pan and zoom control for AvaloniaUI, it can probably be converted to WPF (not a quick and simple but doable task).
https://github.com/wieslawsoltes/Draw2D/blob/c00a2bfc0aad0a0a13396da6623e6652ae4caaa8/src/Draw2D/Controls/ZoomControl.cs#L16
