### ISSUE TITLE
Core2D for web

### ISSUE THREAD

**Issue by Prakash19921206** [wieslawsoltes/Core2D#124]
Hi, 
Thanks for this nice library. Nice to see plenty of features.

i was wondering if there is any plans to implement this library(or just drawing and selection tools) in web, so that it can be embeded in web page.
or is there any such library already.

Thanks & Regards
Prakash

**Comment by wieslawsoltes** [comment]
No plans right now.

**Comment by wieslawsoltes** [comment]
Closing as it's not planned feature.
