### ISSUE TITLE
Controls overlapping on MacOS

### ISSUE THREAD

**Issue by shadeglare** [wieslawsoltes/Core2D#125]
I'm running Core2D 0.10.0-preview6 on MacOS 11.0.1 and have this problem. As a new user I could not find out how to draw anything because didn't notice that the app controls are behind the system window controls.
<img width="239" alt="Screenshot 2021-01-06 at 17 30 28" src="https://user-images.githubusercontent.com/995484/103779618-11692100-5045-11eb-904d-d7aa2d2a40aa.png">

**Comment by wieslawsoltes** [comment]
Please try master branch and let me know if it fixes the issue.

https://dev.azure.com/wieslawsoltes/GitHub/_build/results?buildId=6097&view=artifacts&pathAsName=false&type=publishedArtifacts
