### ISSUE TITLE
Clipping of render area while zooming

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/Core2D#134]
Thanks for the opportunity to try Core2D! 
It looks cool🚀

I couldn't figure out how to create any shape, so I just dragged my svg onto the canvas and found a bug when zooming

![image](https://user-images.githubusercontent.com/29205560/133377179-f37f7ad0-a6c7-4474-98a9-b0921f6a68d9.png)

I attach myself svg
```XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 25.4.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Слой_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1739.5 1562.9" style="enable-background:new 0 0 1739.5 1562.9;" xml:space="preserve">
<path d="M854.2,0C458.9-3.1,86.9,280.1,0,648c-83.8,324,54.3,688.2,340.2,881.9c284.2,200.5,695.6,217.2,993.1,33
	c292.3-173.4,461.9-516.8,406.2-842.3c-50.1-330.2-321-619.1-662.6-695.5C1004.2,7.8,929.2-0.5,854.2,0L854.2,0z M870.5,91.4
	c367.4-3.5,711,272.4,770.2,618.6c62.7,312.7-105.8,653.4-402.7,801c-303.5,159.4-713.4,99.7-949-144.3
	C47.4,1128.8,0.4,734.2,186.6,453.1C328.1,230.2,596.6,85.4,870.5,91.4L870.5,91.4z M847.5,173.7c-338.3,0-648.2,267.2-684.6,588.1
	c-43.3,300.8,155,614.5,455.7,715.4c284.9,102.8,633,5.3,810.8-231.8c191.9-242.6,180.9-610.6-33.1-837.8
	C1261.3,257.7,1055.1,168.1,847.5,173.7L847.5,173.7z M875.6,263.3c299.4,0,572.3,241.1,595.1,526.1c31.2,271.5-164,548.4-442,617.9
	c-267.9,74.6-579.8-49.5-706.7-288.2c-136.6-241.2-66.5-571.3,167.1-734.7C598.6,303.8,737.2,260.2,875.6,263.3L875.6,263.3z
	 M441.6,508.7v640.1h839.2V508.7H441.6L441.6,508.7z M628,608.7h466.3c-82.6,50.8-165.2,162.4-247.8,174.6
	C773.7,725.1,700.8,666.9,628,608.7L628,608.7z M1180.9,667.6v381.2H541.4V667.6C648,752.8,754.5,838,861.1,923.1
	C967.7,837.9,1074.3,752.8,1180.9,667.6L1180.9,667.6z"/>
</svg>

```

**Comment by wieslawsoltes** [comment]
It's know issue. 

I am working on optimizing performance of rendering surface and this is current issue.

**Comment by wieslawsoltes** [comment]
> I couldn't figure out how to create any shape, so I just dragged my svg onto the canvas and found a bug when zooming

Use `Tool` menu with icons.

![image](https://user-images.githubusercontent.com/2297442/133378066-653af8e4-2a70-4032-b5d0-89c35e3ae33a.png)

**Comment by RomanSoloweow** [comment]
Anyway, I think you've done a tremendous amount of work. I understand how difficult it is to create editors. You are doing a great thing🙌

**Comment by wieslawsoltes** [comment]
Fixed in https://github.com/wieslawsoltes/Core2D/commit/a90669574bca692f7c260e22f418c19d55920cd3

**Comment by wieslawsoltes** [comment]
Also added toolbar for tool and the top of the window.

![image](https://user-images.githubusercontent.com/2297442/133419575-fb027021-e813-4474-b9d5-1f5f41a4ad23.png)
