### ISSUE TITLE
Application exiting when enter pressed in the scripting window

### ISSUE THREAD

**Issue by kirant400** [wieslawsoltes/Core2D#152]
Core2D.Desktop Application after pressing <Enter Key> in the scripting window an 
Exception thrown: 'System.MethodAccessException' in AvaloniaEdit.dll
'Core2D.Desktop.exe' (CoreCLR: clrhost): Loaded '\src\Core2D.Desktop\bin\Debug\net7.0\win-x64\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[1608] Core2D.Desktop.exe' has exited with code 0 (0x0).

OS used was Windows 10
Version 11.0.0-preview3

**Comment by wieslawsoltes** [comment]
Fixed in master
