### ISSUE TITLE
Electronic schematic 

### ISSUE THREAD

**Issue by kozintsev** [wieslawsoltes/Core2D#49]
How do you think? Can I use the library to create electronic schemes editor?
The library has the functionality on creation of macroobjects (combining simple shapes in a group) and connections?

Thank you for attention!

**Comment by wieslawsoltes** [comment]
Yes. This should be possible. Core2D support complex shapes, connectors and wires.

**Comment by wieslawsoltes** [comment]
Check this sample Logic diagram for what is possible: https://www.dropbox.com/s/f2r4qh68uox3fg5/Logic.project?dl=0
