### ISSUE TITLE
ForHelp

### ISSUE THREAD

**Issue by YaleLing** [wieslawsoltes/Core2D#57]
hi,thanks for sharing the code, it's helpful a lot.And I have some problems.
Can you tell me how to draw a rectangle with an angle? just like the line.
by the way,do you have some guidances for this project?
thanks
yale

**Comment by wieslawsoltes** [comment]
The is no tooling support for drawing rectangle with angle, you can only do this from code by setting matrix transform but hit-testing currently does not support transforms.

Project does not have any guidence since its still work in progress.

**Comment by YaleLing** [comment]
thanks for reply



lingye911122@163.com
 
From: Wiesław Šoltés
Date: 2017-05-19 01:22
To: wieslawsoltes/Core2D
CC: YaleLing; Author
Subject: Re: [wieslawsoltes/Core2D] ForHelp (#57)
The is no tooling support for drawing rectangle with angle, you can only do this from code by setting matrix transform but hit-testing currently does not support transforms.
Project does not have any guidence since its still work in progress.
