### ISSUE TITLE
Missing Typ "ObservableResource"

### ISSUE THREAD

**Issue by Int32Overflow** [wieslawsoltes/Core2D#59]
Hey,

I checked out the git repo, but I can't compile it with Visual Studio 2017. 
Reason: Type "ObservableResource" is missing!

Did you forget to check in this class?

**Comment by wieslawsoltes** [comment]
I am in middle of refactoring, should finish in few hours. Try this tree https://github.com/wieslawsoltes/Core2D/tree/4d0278cf2d2af16db75d4fbd0c658f529cbaa016

**Comment by wieslawsoltes** [comment]
@Int32Overflow Fixed master branch compilation issues.
