### ISSUE TITLE
Export SkiaSharp codes

### ISSUE THREAD

**Issue by JimSEOW** [wieslawsoltes/Core2D#60]
I guess you are aware of _[SkiaSharp Kimona designer](https://www.youtube.com/watch?v=s9dBA_0qNyc)_ and the [github](https://github.com/xamarin/KimonoDesigner)

Instead of exporting as Xml, Json etc. Core2D exports SkiaSharp class
Why?
(a) After using Core2D to design the vector graphics, the exported SkiaSharp codes can be used directly in e.g. creating the background graphics underlying the top layers of UI controls e.g. button.
Eventually, if keyframe is integrated, the exported SkiaSharp codes, provide animating background graphics, more code efficient than animation gif

(b) Alternatively, Code2D is used as a rendering engine that provides the canvas that can be used in e.g. XAML (WPF, UWP, Xamarin Forms). Core2D takes the XML, JSON generated by Core2D desktop.  The engine exposes all the vector objects for further in-program manipulation.

=> I assume you have such vision, it is just a matter of time. 
=> Great job, tested, the drawing is smooth. 

=> **Feedback**. Drawing Text is un-natural. It is not easy to just clicking on the text box to edit the text on site within the Text object.

**Comment by wieslawsoltes** [comment]
@JimSEOW 

a) Well its matter of time and effort. I have already written SkiaSharp renderer so the code is here to use for code gen: https://github.com/wieslawsoltes/Core2D/blob/master/src/Renderer.SkiaSharp/SkiaSharpRenderer.cs

b) That is already possible see the https://github.com/wieslawsoltes/Core2D/tree/master/apps/Core2D.SkiaDemo

As for Text drawing its made this way as I want precise positioning in rectangle bounds. Later you can edit Text properties. Anyway you are supposed to create templates for pages and groups for elements that contain text fields and are data bound. Later you do not draw text only connect data to elements.

**Comment by wieslawsoltes** [comment]
@JimSEOW I have created simplest rendering sample for `SkiaSharp.Views.*`:
https://github.com/wieslawsoltes/Core2D/tree/master/apps/Core2D.SkiaView
https://developer.xamarin.com/api/root/SkiaSharp/

**Comment by JimSEOW** [comment]
@wieslawsoltes 
Curious. I found a Rendering Library based on WPF. How easy to bring this to Core2D or  Cross Platform Avalon?
Can I simply replace  the PresentationCore and PresentationFramework and System.Windows.Presentation? 

How your cross platform library works? when I need to port from WPF to your?

**Comment by wieslawsoltes** [comment]
@JimSEOW 

The main thing to implement for cross-platform Core2D is renderer interface https://github.com/wieslawsoltes/Core2D/blob/master/src/Core2D/Renderer/ShapeRenderer.cs.

I already have WPF renderer https://github.com/wieslawsoltes/Core2D/tree/master/utilities/Core2D.Renderer.Wpf and WPF app https://github.com/wieslawsoltes/Core2D/tree/master/apps/Core2D.Wpf.

I have also several other renderer backends: https://github.com/wieslawsoltes/Core2D/tree/master/utilities see Core2D.Renderer.* projects.

**Comment by JimSEOW** [comment]
@wieslawsoltes [this is the library,](https://github.com/kazuyaujihara/NCDK/tree/master/NCDKDisplay/Renderers)
All refer to WPF for rendering. If you have a time, if you could do a quick glance to see where are the WPF dependency. Will your library covers all these WPF dependencies? It would be great help. 
This is THE ONLY .NET Chemical drawing. but it should be fun

**Comment by wieslawsoltes** [comment]
@JimSEOW Not sure how NCDK and Core2D would fit together. If you could explain what is your desired result in more detail.

**Comment by JimSEOW** [comment]
Your core2D provide zoom and pan and view of this type of image
https://upload.wikimedia.org/wikipedia/commons/5/58/Solanine_chemical_structure.png

**Comment by wieslawsoltes** [comment]
@JimSEOW You can try to use my stand-alone pan and zoom control for WPF https://github.com/wieslawsoltes/PanAndZoom, its also used by Core2D
