### ISSUE TITLE
How do I run the sample Program?

### ISSUE THREAD

**Issue by TheColonel2688** [wieslawsoltes/Core2D#85]
This may be a dumb question, but how do I run the sample program???

- I downloaded the 0.8.0-preview2 release .zip
- Installed .net Core 3 SDK
- Installed VS 2019
- Opened the .sln in VS 2019
- I found the src/UI/Core2D.UI.Avalonia project set it as the startup project. 
- I click run
- It starts to launch and then closes. (No exceptions are thrown or anything.) **(Edit See Below)**

I'm hoping I can use Core2D to build a program to create and edit Electrical Schematics, for Industrial controls. (Not PCB design that is a completely different thing) There really is no good modern option for this anything with a decent feature set is proprietary VERY expensive, and basically, are legacy programs from 20 years ago that have horrible user interfaces. (They pretend to maintain them but it is really a joke)

P.S. Do you plan on adding documentation in the near future?

EDIT:
I spoke to soon. It is throwing an exception but it is getting caught in a try catch.
The exception is 
`"Could not load file or assembly 'SkiaSharp, Version=1.68.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'. The system cannot find the file specified.":"SkiaSharp, Version=1.68.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756"}`

I tried a complete solution rebuild. it did not fix the problem

**Comment by wieslawsoltes** [comment]
Looks like issue with nuget restore. Try restoring nuget packages manually or try building using build.ps1 script.

**Comment by wieslawsoltes** [comment]
@TheColonel2688 I have downloaded https://github.com/wieslawsoltes/Core2D/archive/0.8.0-preview2.zip and built it and run using `Visual Studio 2019 preview 4.0` and `.NET Core 3.0.100-preview-010184` without any problems. 

Make sure you have installed `.NET Core 3.0.100-preview-010184`.

**Comment by wieslawsoltes** [comment]
@TheColonel2688 `P.S. Do you plan on adding documentation in the near future?`

I would like to have good documentation but I do not have much time to work on program itself not to mention the docs.

**Comment by TheColonel2688** [comment]
I got back to this and I was able to get it to build using the PowerShellScript.

**Comment by TheColonel2688** [comment]
@wieslawsoltes Something you may want to consider about the lack of documentation is; people maybe more inclined to contribute code if they know more about the project 

- what is the scope and end goal of the project?
- basic structure of the the program specifically the editor pane and downward through shapes, connectors etc.

I would like to help contribute to parts that would help me build an Electrical Controls Schematic editor, (i have limited free time (maybe 4 to 8 hours a week) but I would like to help if I can. So far perusing through a little at the source code I have gleaned nothing, it's a big program.

**Comment by wieslawsoltes** [comment]
@TheColonel2688 

The core of the program in contained in 3 projects:
https://github.com/wieslawsoltes/Core2D/tree/master/src/Core2D.Model
https://github.com/wieslawsoltes/Core2D/tree/master/src/Core2D.ViewModels
https://github.com/wieslawsoltes/Core2D/tree/master/src/Core2D.Editor

The most important part is in `Core2D.Editor` and the `ProjectEditor` is central point of all behavior.

The other parts are composed by using IoC:
https://github.com/wieslawsoltes/Core2D/blob/9a27b31f8f280155108797624ca253e7e795cdf2/src/Core2D.UI.Avalonia/Program.cs#L79-L85
https://github.com/wieslawsoltes/Core2D/tree/master/src/Core2D.UI.Avalonia/Modules

**Comment by wieslawsoltes** [comment]
@TheColonel2688 

I have create wiki page descring Core2D program architecture: https://github.com/wieslawsoltes/Core2D/wiki/Architecture

**Comment by TheColonel2688** [comment]
Awesome. Thank you this will help alot.
