### ISSUE TITLE
Why it Takes so long To Compile With Corert

### ISSUE THREAD

**Issue by Shadow4walker** [wieslawsoltes/Core2D#90]
When using earlier Version 0.8.3 Released the Corert Compile it with less time than using the latest Avalonia Released 0.9.0 is takes forever to Compile!

**Comment by wieslawsoltes** [comment]
@Shadow4walker I don't know. It's probably some issue with CoreRT. I am not using it lately as it got broken and it takes lot of time to fix CoreRT builds.
