### ISSUE TITLE
.NET Framework 4.0 support

### ISSUE THREAD

**Issue by gitjsdr26** [wieslawsoltes/Core2D#91]
Dear @wieslawsoltes ,
You've done an awesome and impressive work and I'd like to thank you.
Could you tell me if this project could be used to target .Net Framework 4.0 ?

Best regards

**Comment by wieslawsoltes** [comment]
I don't think it's possible to target .NET 4. Tue project has to many dependencies and aims to support netstandatd2.0.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by gitjsdr26** [comment]
Thank you for your answer.
Best regards
