### ISSUE TITLE
Complex diagram like class diagram

### ISSUE THREAD

**Issue by georgiuk** [wieslawsoltes/Core2D#92]
Hello,
I was wondering if a class diagram editor would be possible with Core2D?
Is there any example of Connectors and complex shapes?
Thank you
Kostas

**Comment by wieslawsoltes** [comment]
Here is example project (please change extension from .zip to .project). You can create complex shapes with connectors.

[Class-Diagram-Connectors.project.zip](https://github.com/wieslawsoltes/Core2D/files/4240779/Class-Diagram-Connectors.project.zip)

**Comment by georgiuk** [comment]
Seems promising. Thank you.
However I want to do something like that by code. Can you point me to some example for complex shape built in code?

**Comment by wieslawsoltes** [comment]
Look at the ProjectEditor class it has some factories to create all necessary objects.
* ProjectEditor.ShapeFactory
* ProjectEditor.ContainerFactory
* ProjectEditor.Factory

Doing all complex shapes by code is doable, just don't have any complex example, you can maybe look and `ProjectEditor.OnDropRecordAsGroup`.

**Comment by georgiuk** [comment]
OK. I ll check them out.
Thanks a lot.

**Comment by wieslawsoltes** [comment]
You can also play with factories using C# scripts: https://github.com/wieslawsoltes/Core2D/tree/master/scripts

**Comment by YBAZAN** [comment]
I cannot manage 

> Here is example project (please change extension from .zip to .project). You can create complex shapes with connectors.
> 
> [Class-Diagram-Connectors.project.zip](https://github.com/wieslawsoltes/Core2D/files/4240779/Class-Diagram-Connectors.project.zip)

I cannot open it in the latest version (0.10). I'm also interested in doing such a complex diagram (with visual customizations), but I find hard to find good documentation on how to concretely use your library.
