### ISSUE TITLE
extended.wfp.toolkit problem

### ISSUE THREAD

**Issue by stefmancio** [wieslawsoltes/Core2D#98]
Hi,

I wanted to start using Core2d , in wpf, so i wanted to use the branch WPF.
When i try to  build the solution , it restores the packages and give me problems with
extended.wfp.toolkit

The package is not ok and i see this warning message
Package was restored using .NetFramework ..... instead of target framework .netCoreapp target 3.0 The package may not be fully compatible

What can i  resolve the problem?
Thank you

**Comment by wieslawsoltes** [comment]
Just ignore the warning. The package does not have .NET Core target but it works without any problems.

Please note `WPF` branch is developed anymore and not compatible with `master` branch. Use at your own risk.
