### ISSUE TITLE
Add resize handles

### ISSUE THREAD

**Issue by tqmitaca** [wieslawsoltes/Core2D#99]
Hi,
Congratulations on your project.
Is it possible to add two "handler" (upper-right and lower-left) on shape to facilitate the resize of shape ?

![image](https://user-images.githubusercontent.com/7223615/79324879-8c673600-7f10-11ea-9f3e-c33a69cd3dbf.png)

Thanks
Giovanni

**Comment by wieslawsoltes** [comment]
It's bit tricky for current implementation but doable. If you check the code ellipse shape is created for two points TopLeft and BottomRight. The Core2D has notion of points and shapes are created based to points defining them. This is import distinction specific to Core2D. I am planning to add decorator with resize handler them will manage resizing of shape `points`.

**Comment by tqmitaca** [comment]
Thank you.

**Comment by wieslawsoltes** [comment]
Work in progress:
![2020-04-16_19-58-21](https://user-images.githubusercontent.com/2297442/79490220-d0476180-801c-11ea-95fe-b2d50f695251.gif)

**Comment by wieslawsoltes** [comment]
@tqmitaca Initial support for resize handles was added to `master` branch.

**Comment by wieslawsoltes** [comment]
Resize handles in action:
![2020-04-18_16-03-55](https://user-images.githubusercontent.com/2297442/79639833-664ec980-818e-11ea-8418-70996d377418.gif)

**Comment by wieslawsoltes** [comment]
![2020-04-18_16-08-18](https://user-images.githubusercontent.com/2297442/79639929-ee34d380-818e-11ea-817b-a231eb024751.gif)

**Comment by wieslawsoltes** [comment]
![2020-04-18_16-11-55](https://user-images.githubusercontent.com/2297442/79640006-761add80-818f-11ea-8a12-40c2cb3fa725.gif)

**Comment by tqmitaca** [comment]
Good job.
Thank you
